name: Daily Auto Jackpot Multi-Token

on:
  schedule:
    # 08:30 và 08:45 sáng (giờ VN -> 01:30, 01:45 UTC)
    - cron: '30,45 1 * * *'
    # Từ 09:00 đến 15:45 (mỗi 15 phút) (giờ VN -> 02:00 đến 08:45 UTC)
    - cron: '*/15 2-8 * * *'
    # Đúng 16:00 chiều (giờ VN -> 09:00 UTC)
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run script
        env:
          HUY: ${{ secrets.HUY }}
          LINH: ${{ secrets.LINH }}
          OANH: ${{ secrets.OANH }}
        run: node script.js
