name: Daily Auto Jackpot Multi-Token

on:
  schedule:
    # Chạy mỗi 15 phút, từ 01:30 đến 09:00 UTC (tương đương 08:30 đến 16:00 VN)
    - cron: '*/15 1-9 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run script
        env:
          HUY: ${{ secrets.HUY }}
          LINH: ${{ secrets.LINH }}
          OANH: ${{ secrets.OANH }}
        run: node script.js
